// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/G-V-G/l3/server/generalStore"
	"github.com/G-V-G/l3/server/handlers"
	"github.com/google/wire"
)

// Injectors from build.go:

func NewServer(senv *ServerEnv) (*ForumServer, error) {
	db, err := NewDbConnection()
	if err != nil {
		return nil, err
	}
	generalStoreGeneralStore := generalStore.NewGeneralStore(db)
	handlersHandlers := handlers.NewHandler(generalStoreGeneralStore)
	forumServer := &ForumServer{
		Handlers: handlersHandlers,
		Senv:     senv,
	}
	return forumServer, nil
}

// build.go:

var providers = wire.NewSet(generalStore.NewGeneralStore, handlers.NewHandler)
